[build]
  # ← set this to your actual output folder
  publish = "dist"      # e.g. "build" for CRA, "dist" for Vite, etc.

[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
  force    = true        # optional, ensures it overrides any file match
